### ISSUE TITLE
error[E0425]: cannot find value `W_OK` in crate `libc`

### ISSUE THREAD

**Issue by raycoe** [marcospb19/unix_file_permissions#4]
Hi,

On Windows, get the following error:

Checking permissions v0.4.1
`error[E0425]: cannot find value 'W_OK' in crate 'libc'
   --> C:\Users\dev\.cargo\registry\src\github.com-1ecc6299db9ec823\permissions-0.4.1\src\functions.rs:101:35`
`101 |     access_syscall(&parent, libc::W_OK)`
`    |                                   ^^^^ not found in 'libc'`

cargo --version=1.67.1

Thx

**Comment by marcospb19** [comment]
Thanks for filling the bug report, I thought this was fixed by #3.

Well I don't have a Windows machine to test it so I can't do a lot about it, maybe just update the README notice to say it's broken on Windows.

**Comment by raycoe** [comment]
Just tell me if you want me to test any change

**Comment by raycoe** [comment]
I think I solved the issue by changing few lines in our src/functions.rs:

Line 13
`#[cfg(target_os = "windows")]`
`use crate::consts::W_OK;`

Line 104
`#[cfg(not(target_os = "windows"))]`
`access_syscall(&parent, libc::W_OK)`
`#[cfg(windows)]`
`access_syscall(&parent, W_OK)`

However, requires to be deeply tested

**Comment by hardliner66** [comment]
This sadly breaks the windows build of my tool, so I created an MR fixing it. The code already defined the linux and windows versions of the constants, re-exporting them for the user of the library. I just had to use the values that already existed.

**Comment by marcospb19** [comment]
I gave up on Windows and added a note in README, crates.io/crates/permissions and docs.rs/permissions pointing Windows users to [`faccess`] instead.

I was willing to merge the [`faccess`] functionality in this crate but the folks didn't answer me so that's the best I can do.

I hope that it fulfills your needs! Thanks to you both for helping with issue reporting.

[`faccess`]: https://crates.io/crates/faccess
